#-----------------------------------
--- # Application
#-----------------------------------

spring:
  application:
    name: TALENT_CENTER_79
  profiles:
    active:
      - "@spring.profiles.active@"
  main:
    lazy-initialization: false
server:
  port: 8081

--- ## Production

spring:
  config:
    activate:
      on-profile: "production"
  main:
    lazy-initialization: true

#-----------------------------------
--- # i18n & L10n
#-----------------------------------

spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages

#-----------------------------------
--- # Logging
#-----------------------------------

logging:
  level:
    com:
      tujuhsembilan: TRACE

--- ## Production

spring:
  config:
    activate:
      on-profile: "production"
logging:
  level:
    com:
      tujuhsembilan: INFO

#-----------------------------------
--- # Miscellanous
#-----------------------------------

spring:
  output:
    ansi:
      enabled: always

# # -----------------------------------
--- # Database
# # -----------------------------------

spring:
   ##Datasource
   datasource:
      #URL EXTERNAL
      # url: jdbc:postgresql://cloudias79.com:5545/new_db_talentcenter
      # url: jdbc:postgresql://10.10.5.180:5432/new_db_talentcenter
      url: jdbc:postgresql://localhost:5432/talent_center

      # username: usrtalentcenter
      # password: m1QVs3zKymgPduz

      username: postgres
      password: root


      driverClassName: org.postgresql.Driver
   jpa: 
      hibernate: 
         ddl-auto: validate
      show-sql: true
      properties: 
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            # default-batch-fetch-size: 10
            # enable-lazy-load-no-trans: true
            # format-sql: true
            # use-sql-comments: true
      # open-in-view: false    

# spring.jpa.open-in-view=false
# spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
            # spring.jpa.properties.hibernate.default_batch_fetch_size=10
           
  
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: ERROR
#         type:
#           descriptor:
#             sql:
#               BasicBinder: TRACE


#-----------------------------------
--- # Minio
#-----------------------------------

application:
   minio:
      url: https://minio.cloudias79.com/
      username: devtalentcenter
      password: as4Dx6L4Uf1zFkyy
      bucket-name: talent-center-app

#-----------------------------------
--- # Elastic Search
#-----------------------------------

spring:
   elasticsearch:
      uris: "http://localhost:9201"
      socket-timeout: "10s"
      username: "yanax"
      password: "123456"
     
   main:
      allow-bean-definition-overriding: true


      