#-----------------------------------
--- # Application
#-----------------------------------

spring:
  application:
    name: TALENT_CENTER_79
  profiles:
    active:
      - "@spring.profiles.active@"
  main:
    lazy-initialization: false
server:
  port: 8081

--- ## Production

spring:
  config:
    activate:
      on-profile: "production"
  main:
    lazy-initialization: true

#-----------------------------------
--- # i18n & L10n
#-----------------------------------

spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages

#-----------------------------------
--- # Logging
#-----------------------------------

logging:
  level:
    com:
      tujuhsembilan: TRACE

--- ## Production

spring:
  config:
    activate:
      on-profile: "production"
logging:
  level:
    com:
      tujuhsembilan: INFO

#-----------------------------------
--- # Miscellanous
#-----------------------------------

spring:
  output:
    ansi:
      enabled: always

# # -----------------------------------
--- # Database
# # -----------------------------------

spring:
   ##Datasource
   datasource:
      #URL EXTERNAL
      # url: jdbc:postgresql://cloudias79.com:5545/new_db_talentcenter
      url: jdbc:postgresql://10.10.5.180:5432/new_db_talentcenter
      # url: jdbc:postgresql://localhost:5432/talent_center

      username: usrtalentcenter
      password: m1QVs3zKymgPduz

      # username: postgres
      # password: root


      driverClassName: org.postgresql.Driver
   jpa: 
      hibernate: 
         ddl-auto: validate
      show-sql: true
      properties: 
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format-sql: true
            use-sql-comments: true
           
  
logging:
  level:
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: TRACE